### ISSUE TITLE
Почему необходимо указывать target_name?

### ISSUE THREAD

**Issue by SolaBe** [vlajnaya-mol/message-analyser#10]
Как я понимаю target_name подставляется вместо имени собеседника в списке сообщений и отображается на графиках. Как по мне это не совсем информативно. И как это работает в групповых чатах?

**Comment by voloha-mil** [comment]
target_name нужно указывать чтобы правильно распарсить файл с сообщениями с ВКонтакте. Для Телеграма это не столь важно (влияет лишь на подписи на графиках), потому что собеседников 2 и определить кто есть кто можно просто по target_id. Груповые чаты пока не поддерживаются, но планирую скоро заняться этим.
