### ISSUE TITLE
Нет интернета/База заблокированна

### ISSUE THREAD

**Issue by alfacom** [vlajnaya-mol/message-analyser#2]
Пытаюсь проанализировать сообщения в телеге.
На этапе ввода api id и т.д. ругается, что нет интернета или база заблокирована.
![image](https://user-images.githubusercontent.com/1672524/53288003-63c43000-3794-11e9-9210-7fda7b6ec4d3.png)

И пара вопросов. Your name/Target's name это какие-то уникальные идентификаторы из телеги? В каком формате вводить номер телефона и что за параметр Code после него?
![image](https://user-images.githubusercontent.com/1672524/53288037-ef3dc100-3794-11e9-969a-27095d49ad71.png)

**Comment by voloha-mil** [comment]
Такая проблема возникала, когда я пытался запустить два процеса анализатора одновременно. Удостоверься, что есть интернет и включи Телеграм.

Your name/Target's name это просто имена. Их правильность важна только если ты парсишь файл с ВКонтакте. Формат номера - полный формат из префиксом страны, без дефисов и скобок. Code придет после нажатия 'Continue'

**Comment by Siblingvv** [comment]
> 
> 
> Такая проблема возникала, когда я пытался запустить два процеса анализатора одновременно. Удостоверься, что есть интернет и включи Телеграм.
> 
> Your name/Target's name это просто имена. Их правильность важна только если ты парсишь файл с ВКонтакте. Формат номера - полный формат из префиксом страны, без дефисов и скобок. Code придет после нажатия 'Continue'

То есть я указываю логин из телеги, или как человек у меня указан?
Также что насчет удаленного аккаунта? Он помечен у меня как Deleted Account, но вся переписка сохранена.

**Comment by voloha-mil** [comment]
> То есть я указываю логин из телеги, или как человек у меня указан?
> Также что насчет удаленного аккаунта? Он помечен у меня как Deleted Account, но вся переписка сохранена.

Ты указываешь chat_id. Просто выбери нужный чат в выпадающем списке на предпоследнем окне, вручную ID писать не нужно.

**Comment by Siblingvv** [comment]
> 
> 
> Такая проблема возникала, когда я пытался запустить два процеса анализатора одновременно. Удостоверься, что есть интернет и включи Телеграм.
> 
> Your name/Target's name это просто имена. Их правильность важна только если ты парсишь файл с ВКонтакте. Формат номера - полный формат из префиксом страны, без дефисов и скобок. Code придет после нажатия 'Continue'

`C:\Users\User>cd C:\Installed\Lubovash\message-analyser-master

C:\Installed\Lubovash\message-analyser-master>python main.py
2019-02-23 21:29:59,352 - Session parameters were received from C:\Installed\Lubovash\message-analyser-master\config.ini file.

2019-02-23 21:30:10,758 - Telegram secrets were received from C:\Installed\Lubovash\message-analyser-master\config.ini file.

Task exception was never retrieved
future: <Task finished coro=<MessageAnalyserGUI.raise_telegram_auth_frame.<locals>.try_sign_in_and_continue() done, defined at C:\Installed\Lubovash\message-analyser-master\message_analyser\GUI.py:295> exception=OperationalError('database is locked',)>
Traceback (most recent call last):
  File "C:\Installed\Lubovash\message-analyser-master\message_analyser\GUI.py", line 301, in try_sign_in_and_continue
    loop=self.aio_loop)
  File "C:\Installed\Lubovash\message-analyser-master\message_analyser\retriever\telegram.py", line 44, in get_sign_in_results
    client = TelegramClient(session_name, api_id, api_hash, loop=loop)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\telethon\client\telegrambaseclient.py", line 223, in __init__
    DEFAULT_PORT
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\telethon\sessions\sqlite.py", line 186, in set_dc
    self._update_session_table()
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\telethon\sessions\sqlite.py", line 207, in _update_session_table
    c.execute('delete from sessions')
sqlite3.OperationalError: database is locked
2019-02-23 21:31:24,418 - No Internet connection.`

Всё та же проблема. Ввел свое имя, чужое имя, апишные штуки, телефон, жму Continue и получаю ошибку такую.

Решения еще нет?

**Comment by Siblingvv** [comment]
Проблему решил, пустив трафик через ВПН (PIA).
РКН блокирует апи телеграма в России)

**Comment by voloha-mil** [comment]
Хорошо :)
